##
## sun386 linkops makefile
##
## File    : makefile.386
##
## Copyright 1990, 1991 INMOS Limited
##
## Date    : 3/27/91
## Version : 1.1
##
## 06/12/90 dave edwards - originated
## 22/01/91 dave edwards - altered to make linkios directory at outer level
## 23/01/91 dave edwards - put in bob's new link modules & header files
##

LINKIOS= ../../linkios/386

CC=cc -c
LINK=cc -o
HOST=SUN386
OS=SUNOS
COMMS=SUNTCP
END=LITTLE_ENDIAN
CFLAGS= -D`arch` -I$(LINKIOS) -DNODELAY
O=.o
E=

##uncomment line below for tcp linkops support
TCP =-DOPStcp
TMODULE = tops$(O)

##uncomment next 2 lines for tcplink linkio support
LMODULE1 = tcplink$(O)
L1 = -DLNKtcp

##uncomment next 2 lines for b008 support
LMODULE2 = $(LINKIOS)s386link$(O)
L2 = -DS386

LINKMODULES= $(LMODULE1) $(LMODULE2)
LINKFLAGS = $(L1) $(L2)

DFLAGS= -D$(HOST) -D$(OS) -D$(COMMS) -D$(END) $(TCP) $(LINKFLAGS) -DMES

#define objects
OPSOBJECTS=linkops$(O) lops$(O) $(TMODULE) metlnkio$(O) conlib$(O) lmethod$(O) \
           debug$(O) $(LMODULE1) 
OBJECTS=$(OPSOBJECTS) $(LINKMODULES)

#final dependancy
all: $(OPSOBJECTS)

clean:
	rm $(OPSOBJECTS)

#debug dependancies to produce object
debug$(O): debug.c types.h
	$(CC)  $(CFLAGS) $(DFLAGS) debug.c

#lmethod dependanices to produce object
lmethod$(O): lmethod.c lmethod.h
	$(CC)  $(CFLAGS) $(DFLAGS) lmethod.c

#conlib dependancies to produce object
conlib$(O): conlib.c conlib.h debug.h opserror.h lmethod.h types.h
	$(CC)  $(CFLAGS) $(DFLAGS) conlib.c

#metlnkio dependancies to produce object
metlnkio$(O): metlnkio.c lmethod.h opserror.h types.h conlib.h $(LINKIOS)/linkio.h
	$(CC)  $(CFLAGS) $(DFLAGS) metlnkio.c 

#tcplinkio dependancies to produce object
tcplink$(O): tcplink.c types.h debug.h opsprot.h opserror.h $(LINKIOS)/linkio.h
	$(CC) $(CFLAGS) $(DFLAGS) tcplink.c
                                                                                                    
#lops dependancies to produce object                                                   
lops$(O): lops.c lops.h types.h linkops.h hbeat.h opserror.h lmethod.h conlib.h debug.h $(LINKIOS)/linkio.h
	$(CC)  $(CFLAGS) $(DFLAGS) lops.c

#tops dependancies to produce object
tops$(O): tops.c tops.h linkops.h hbeat.h opsprot.h opserror.h types.h conlib.h debug.h
	$(CC)  $(CFLAGS) $(DFLAGS) tops.c
 
#linkops dependancies to produce object
linkops$(O): linkops.c linkops.h lops.h tops.h opserror.h lmethod.h types.h debug.h conlib.h
	$(CC)  $(CFLAGS) $(DFLAGS) linkops.c
