/*
-- ----------------------------------------------------------------------------
--
--     SCCS ID : @(#)  boards.inc 1.3 91/08/15 10:44:41
--
--     Object Name : boards.inc
--     Revision    : 1.3
--
--     (c) Copyright INMOS Limited.
--     All Rights Reserved.
--
--     DESCRIPTION
--         Include file of INMOS evaluation board definitions.
--
--     NOTES
--         None.
--
--     HISTORY
--         1-Jun-1990    Antony King    Created file.
--
-- ----------------------------------------------------------------------------
*/

/*{{{  Transputer evaluation boards */
define t414 (memory =  64k) b001;
define t414 (memory =   2m) b002;
define t414 (memory =   1m) b002_1m;
define t414 (memory =   2m) b002_2m;
define t414 (memory =   2m) b004;
define t212 (memory =  64k) b005;
define t212 (memory =   2k) b006;
define t212 (memory =   2k) b007;
define t222 (memory =   4k) b008;
define t212 (memory =  64k) b009;
define t414 (memory =   1m) b010;
define t800 (memory =   2m) b011;
define t222 (memory =   4k) b012;
define t212 (memory =   2k) b012_t212;
define t222 (memory =   4k) b012_t222;
define t222 (memory =   4k) b014;
define t212 (memory =   2k) b014_t212;
define t222 (memory =   4k) b014_t222;
define t801 (memory = 256k) b016;
define t222 (memory =  56k - 512) b018;

define T414 (memory =  64K) B001;
define T414 (memory =   2M) B002;
define T414 (memory =   1M) B002_1M;
define T414 (memory =   2M) B002_2M;
define T414 (memory =   2M) B004;
define T212 (memory =  64K) B005;
define T212 (memory =   2K) B006;
define T212 (memory =   2K) B007;
define T222 (memory =   4K) B008;
define T212 (memory =  64K) B009;
define T414 (memory =   1M) B010;
define T800 (memory =   2M) B011;
define T222 (memory =   4K) B012;
define T212 (memory =   2K) B012_T212;
define T222 (memory =   4K) B012_T222;
define T222 (memory =   4K) B014;
define T212 (memory =   2K) B014_T212;
define T222 (memory =   4K) B014_T222;
define T801 (memory = 256K) B016;
define T222 (memory =  56K - 512) B018;
/*}}}*/
